[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_twiter = "6ar8YVWcscGV93PfEdkT2R67Np7TAxwtAX7mD6wtQJeK"

[programs.devnet]
solana_twiter = "6ar8YVWcscGV93PfEdkT2R67Np7TAxwtAX7mD6wtQJeK"

[programs.mainnet]
solana_twiter = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/manjotssandhu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy-idl = "mkdir -p app/src/idl && cp target/idl/solana_twiter.json app/src/idl/solana_twiter.json"
